name: install-opendylan
description: Install the Open Dylan compiler and tools
inputs:
  tag:
    required: false
    type: string
    default: v2023.1.0

runs:
  using: composite
  steps:
    - name: Install Open Dylan
      env:
        OD_TAG: ${{ inputs.tag }}
      shell: bash
      run: |
        echo "Installing Open Dylan..."
        od_version=$(echo ${{ inputs.tag }} | sed -En 's/v([0-9]+\.[0-9]+)\.[0-9]+/\1/p')
        opsys=$(uname -s | tr '[:upper:]' '[:lower:]')
        env | sort  # debug
        url="https://github.com/dylan-lang/opendylan/releases/download/${OD_TAG}/opendylan-${od_version}-x86_64-${opsys}.tar.bz2"
        echo "Downloading from ${url}"
        mkdir _od
        cd _od
        curl -L -o opendylan.tar.bz2 ${url}
        tar xfj opendylan.tar.bz2
        ln -s opendylan-${od_version} opendylan
        ln -s opendylan-${od_version}/bin/dylan-compiler
        ln -s opendylan-${od_version}/bin/dylan
        echo "Compiler: ${PWD}/dylan-compiler"
        echo "dylan-tool: ${PWD}/dylan"
        echo -n "Open Dylan "
        ./dylan-compiler -version
        echo -n "dylan-tool version: "
        ./dylan version
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path
        # Eventually we can add opendylan/bin to the path instead of creating
        # links in the current directory, but for now there are too many
        # non-Dylan programs in opendylan/bin.
        echo "${PWD}" >> ${GITHUB_PATH}
