# To test changes to the install-opendylan Action we choose an arbitrary, relatively
# simple project to build and test.

name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main

  # This enables the Run Workflow button here:
  # https://github.com/dylan-lang/install-opendylan/actions/workflows/build-and-test.yml
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v7

      - uses: actions/checkout@v7
        with:
          repository: dylan-lang/hash-algorithms
          path: hash-algorithms

      # Use the local checkout of install-opendylan as a GitHub Action.
      - uses: ./

      - name: Update workspace
        run: |
          cd hash-algorithms
          deft update

      - name: Run test suite
        run: |
          cd hash-algorithms
          deft test -- --report surefire --report-file _build/test-output.xml

      - name: Publish test report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v6
        with:
          report_paths: '**/_build/test-output.xml'
          detailed_summary: true
          include_passed: true
